export enum ACTIONS_TYPE {
    SET_AUTH_USER_DATA = 'SET_AUTH_USER_DATA',

    SET_CONTACTS = "SET_CONTACTS",
    ADD_CONTACT = 'ADD_CONTACT',
    CHANGE_CONTACT_NAME = 'CHANGE_CONTACT_NAME',
    CHANGE_EDIT_MODE = 'CHANGE_EDIT_MODE',
    DELETE_CONTACT = 'DELETE_CONTACT',
}